site_name: PZFlow
repo_url: https://github.com/jfcrenshaw/pzflow
nav:
  - Home: index.md
  - Install: install.md
  - Tutorials: tutorials/index.md
  - Common gotchas: gotchas.md
  - API: API/

theme:
  name: material
  palette:
    scheme: slate
    primary: pink
    accent: deep orange
  icon:
    logo: material/star-face
  features:
    - navigation.indexes
plugins:
  - search
  - mkdocs-jupyter:
      theme: dark
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - literate-nav
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
extra:
  version:
    provider: mike
